name: Run Quick Executable Test
description: Run a simple test to ensure the built executable launches
runs:
  using: "composite"
  steps:
    - name: Run test on Windows
      if: runner.os == 'Windows'
      shell: cmd
      run: |
        if exist .\bin\flow_broker_server.exe (
          echo Server binary found
        ) else (
          echo Server binary not found & exit 1
        )
    - name: Run client test on Windows
      if: runner.os == 'Windows'
      shell: cmd
      run: |
        if exist .\bin\flow_broker_client.exe (
          echo Client binary found
        ) else (
          echo Client binary not found & exit 1
        )
    - name: Run test on Linux
      if: runner.os == 'Linux'
      shell: bash
      run: |
        if [ -x ./bin/flow_broker_server ]; then
          echo "Server binary found"
        else
          echo "Server binary not found" >&2
          exit 1
        fi
    - name: Run client test on Linux
      if: runner.os == 'Linux'
      shell: bash
      run: |
        if [ -x ./bin/flow_broker_client ]; then
          echo "Client binary found"
        else
          echo "Client binary not found" >&2
          exit 1
        fi